apiVersion: apps/v1
kind: Deployment
metadata:
  name: trippricer
  labels:
    app: trippricer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trippricer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: trippricer
    spec:
      containers:
        - name: trippricer
          image: heiwait/trippricer-exposition:9f450114
          ports:
            - containerPort: 12378
          env:
            - name: LOG_PATH
              value: "."
---
apiVersion: v1
kind: Service
metadata:
  name: trippricer-svc
spec:
  selector:
    app: trippricer
  ports:
    - name: http
      protocol: TCP
      port: 12378
      targetPort: 12378
  externalIPs:
    - 173.212.241.172