INSERT INTO DESTINATION (NAME) VALUES ('Paris');
INSERT INTO DESTINATION (NAME) VALUES ('Lille');
INSERT INTO DESTINATION (NAME) VALUES ('Beijing');
INSERT INTO DESTINATION (NAME) VALUES ('New-york');
INSERT INTO DESTINATION (NAME) VALUES ('New-Tokyo');