apiVersion: v1
kind: Service
metadata:
  name: {{ include "trippricer.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "trippricer.selectorLabels" . | nindent 4 }}
  externalIPs:
    - {{ .Values.service.externalIPs }}